
/*
AUTONOMOUS ROUTES
1. LEFT QUALS AUTO 
2. RIGHT QUALS AUTO 
3. FULL WP AUTO
4. LEFT ELIMS AUTO
5. RIGHT ELIMS AUTO 
6. TUNING AUTO
7. SKILLS AUTO
8. LEFT RUSH AUTO 
9. RIGHT RUSH AUTO 
*/

// AUTONOMOUS
#define RUN_THIS_AUTO 3
#define TOTAL_AUTONOMOUS_ROUTES 9

// DEFINE MOTORS HERE
#define FRONT_LEFT_DRIVEBASE -11
#define MID_LEFT_DRIVEBASE -12
#define BACK_LEFT_DRIVEBASE 13

#define FRONT_RIGHT_DRIVEBASE -18
#define MID_RIGHT_DRIVEBASE 19
#define BACK_RIGHT_DRIVEBASE 20

#define BOT_STAGE_FULL 17
#define BOT_STAGE_HALF 15
#define TOP_STAGE -14

// DEFINE SENSORS HERE
#define IMU_SENSOR 10
#define DISTANCE_SENSOR_LEFT 1
#define DISTANCE_SENSOR_RIGHT 9
#define DISTANCE_SENSOR_BACK 2
#define VERTICAL_ROTATION_ODOM 3
#define HORIZONTAL_ROTATION_ODOM -8

#define IMU_SCALE 1.018f
#define H_POD_SCALE 0.95f
#define V_POD_SCALE 1.0f

// DEFINE PNEUMATICS HERE
#define WING 'H'
#define SCRAPER 'F'
#define PREROLLER_LIFT 'E'
#define HOOD_P 'G'

// DEFINE DRIVEBASE SETTINGS HERE
#define TRACKWIDTH 10.4
#define RPM 450
#define WHEEL_DIAMETER 3.25

// DRIVEBASE PID VALUES
#define MOVE_DISTANCE_P 8.0

#define LATERAL_KP 8.5
#define LATERAL_KI 0
#define LATERAL_KD 40

////////
#define ANGULAR_KP 3.6
#define ANGULAR_KI 0
#define ANGULAR_KD 20.75

//RAMSETE VALUES
#define BETA 0.0171
#define ZETA 0.7
#define KV 2.31
#define KMAX 3.5

//SE2 VALUES
#define KX 5.2
#define KY 4.0
#define KTH 1.3

// OFFSETS
#define HORIZONTAL_ODOM_OFFSET 0.5
#define VERTICAL_ODOM_OFFSET 0

// OTHER PID SETTINGS
#define LATERAL_ANTIWINDUP 3
#define LATERAL_SMALL_ERROR 0.5
#define LATERAL_LARGE_ERROR 3
#define LATERAL_SMALL_ERROR_TIMEOUT 20
#define LATERAL_LARGE_ERROR_TIMEOUT 500
#define LATERAL_SLEW 0

#define ANGULAR_ANTIWINDUP 3
#define ANGULAR_SMALL_ERROR 1.0
#define ANGULAR_LARGE_ERROR 3
#define ANGULAR_SMALL_ERROR_TIMEOUT 20
#define ANGULAR_LARGE_ERROR_TIMEOUT 500
#define ANGULAR_SLEW 0

// UNJAM + COLOR SORT
#define COLOR_PROX_MIN 50
#define RED_HUE_LOW 30.0
#define RED_HUE_HIGH 330.0
#define BLUE_HUE_LOW 180.0
#define BLUE_HUE_HIGH 260.0
#define COLOR_EJECT_DELAY_MS 300
#define COLOR_EJECT_OUT_MS 500
#define COLOR_EJECT_IN_MS 700

#define JAM_CURRENT_MA 2400
#define JAM_DETECT_MS 3000
#define UNJAM_OUTTAKE_MS 150
#define UNJAM_INTAKE_MS 300