
/*
AUTONOMOUS ROUTES
1. LEFT QUALS AUTO
2. RIGHT QUALS AUTO
3. FULL WP AUTO
4. LEFT ELIMS AUTO
5. RIGHT ELIMS AUTO
6. TUNING AUTO
7. SKILLS AUTO
8. LEFT RUSH AUTO
9. RIGHT RUSH AUTO
*/

// AUTONOMOUS
#define RUN_THIS_AUTO 5
#define TOTAL_AUTONOMOUS_ROUTES 9

// DEFINE MOTORS HERE
#define FRONT_LEFT_DRIVEBASE -11
#define MID_LEFT_DRIVEBASE -12
#define BACK_LEFT_DRIVEBASE 13

#define FRONT_RIGHT_DRIVEBASE -18
#define MID_RIGHT_DRIVEBASE 19
#define BACK_RIGHT_DRIVEBASE 20

#define CONVEYOR_MOTOR -1
#define HOOD_ROLLER_MOTOR 10

// DEFINE SENSORS HERE
#define IMU_SENSOR 8
#define DISTANCE_SENSOR_LEFT 3
#define DISTANCE_SENSOR_RIGHT 9
#define DISTANCE_SENSOR_FRONT 4
#define COLOR_SENSOR_HOOD 3
#define VERTICAL_ROTATION_ODOM -17
#define HORIZONTAL_ROTATION_ODOM 15

// DEFINE PNEUMATICS HERE
#define WING 'B'
#define SCRAPER 'H'
#define PARK 'C'
#define PARKCLAMP 'D'
#define HOODPISTON 'A'

// DEFINE DRIVEBASE SETTINGS HERE
#define TRACKWIDTH 11.4
#define RPM 450
#define WHEEL_DIAMETER 3.25

// DRIVEBASE PID VALUES
#define MOVE_DISTANCE_P 8.0

#define LATERAL_KP 9.5
#define LATERAL_KI 0
#define LATERAL_KD 41

#define ANGULAR_KP 3.2
#define ANGULAR_KI 0
#define ANGULAR_KD 22

//RAMSETE VALUES
#define BETA 0.0171
#define ZETA 0.7
#define KV 2.31
#define KMAX 3.5

//SE2 VALUES
#define KX 5.2
#define KY 4.0
#define KTH 1.3

// OFFSETS
#define HORIZONTAL_ODOM_OFFSET -5.0
#define VERTICAL_ODOM_OFFSET 0.2

// OTHER PID SETTINGS
#define LATERAL_ANTIWINDUP 3
#define LATERAL_SMALL_ERROR 0.5
#define LATERAL_LARGE_ERROR 3
#define LATERAL_SMALL_ERROR_TIMEOUT 20
#define LATERAL_LARGE_ERROR_TIMEOUT 500
#define LATERAL_SLEW 0

#define ANGULAR_ANTIWINDUP 3
#define ANGULAR_SMALL_ERROR 1.0
#define ANGULAR_LARGE_ERROR 3
#define ANGULAR_SMALL_ERROR_TIMEOUT 20
#define ANGULAR_LARGE_ERROR_TIMEOUT 500
#define ANGULAR_SLEW 0

// UNJAM + COLOR SORT
#define COLOR_PROX_MIN 50
#define RED_HUE_LOW 30.0
#define RED_HUE_HIGH 330.0
#define BLUE_HUE_LOW 180.0
#define BLUE_HUE_HIGH 260.0
#define COLOR_EJECT_DELAY_MS 300
#define COLOR_EJECT_OUT_MS 500
#define COLOR_EJECT_IN_MS 700

#define JAM_CURRENT_MA 2400
#define JAM_DETECT_MS 1200
#define UNJAM_OUTTAKE_MS 350
#define UNJAM_INTAKE_MS 500